class ErrorCodes:
    """Central list of error codes used across the app, grouped by module (auth, user, appointment) for easy tracking in logs."""
    INVALID_CREDENTIALS = "AUTH_1001"
    TOKEN_EXPIRED = "AUTH_1002"
    INVALID_TOKEN = "AUTH_1003"
    ACCOUNT_DEACTIVATED = "AUTH_1004"
    INSUFFICIENT_PERMISSIONS = "AUTH_1005"

    USER_NOT_FOUND = "USER_1101"
    USER_ALREADY_EXISTS = "USER_1102"
    INVALID_USER_DATA = "USER_1103"

    APPOINTMENT_NOT_FOUND = "APP_1201"
    SLOT_NOT_AVAILABLE = "APP_1202"
    DOUBLE_BOOKING = "APP_1203"
    PAST_DATE_BOOKING = "APP_1204"
    CANCELLATION_NOT_ALLOWED = "APP_1205"
    APPOINTMENT_ALREADY_COMPLETED = "APP_1206"

    DOCTOR_NOT_FOUND = "DOC_1301"
    DOCTOR_UNAVAILABLE = "DOC_1302"

    PAYMENT_FAILED = "PAY_1401"

    VALIDATION_ERROR = "VAL_1501"
    INVALID_INPUT = "VAL_1502"

    DATABASE_ERROR = "DB_1601"
    DUPLICATE_ENTRY = "DB_1602"

    INTERNAL_ERROR = "GEN_9001"
    SERVICE_UNAVAILABLE = "GEN_9002"
