spring.application.name=backend

# Here I set the server port to 8080, you can change it if needed
server.port=8080

# Database configuration for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/its_db
spring.datasource.username=postgres
spring.datasource.password=1234567

# Hibernate configuration because we want to use JPA for ORM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Specify the Hibernate dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect







