# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/its_db
spring.datasource.username=postgres
spring.datasource.password=1234567
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=ats_super_secret_key_must_be_32chars_min
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000
jwt.refresh-token-days=7

# Default HR credentials
app.hr.email=hr@gmail.com
app.hr.password=Admin@123
app.hr.name=HR Admin

# Logging
logging.level.com.ats=DEBUG
logging.level.org.hibernate.SQL=DEBUG
