package com.interview_tracking_system.backend.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

@Entity
@Table(name = "panel", indexes = {
        @Index(name = "idx_panel_email", columnList = "email")
})
public class Panel {

    /** Maximum character length for name and designation fields. */
    private static final int NAME_LENGTH = 100;

    /** Maximum character length for email fields. */
    private static final int EMAIL_LENGTH = 150;

    /** Maximum character length for mobile number fields. */
    private static final int MOBILE_LENGTH = 15;

    /** Maximum character length for organization name fields. */
    private static final int ORG_LENGTH = 150;

    /** Unique identifier for the panel member, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Full name of the panel member. Cannot be null. */
    @Column(name = "full_name", nullable = false, length = NAME_LENGTH)
    private String fullName;

    /** Email address of the panel member. Must be unique and cannot be null. */
    @Column(nullable = false, unique = true, length = EMAIL_LENGTH)
    private String email;

    /** Mobile phone number of the panel member. */
    @Column(length = MOBILE_LENGTH)
    private String mobile;

    /** Name of the organization the panel member belongs to. */
    @Column(length = ORG_LENGTH)
    private String organization;

    /** Job designation or title of the panel member. */
    @Column(length = NAME_LENGTH)
    private String designation;

    /** Hashed password used for authentication. */
    @Column(length = 255)
    private String password;

    /**
     * Indicates whether the panel member's account is active.
     * Defaults to {@code false} until the account is activated via email.
     */
    @Column(nullable = false)
    private boolean active = false;

    /** Token sent to the panel member's email for account activation. */
    @Column(length = 255)
    private String activationToken;

    /** Expiry date and time of the activation token. */
    private LocalDateTime tokenExpiry;

    /** Timestamp of when this panel member record was created. */
    private LocalDateTime createdAt;

    /** Timestamp of when this panel member record was last updated. */
    private LocalDateTime updatedAt;

    /**
     * Returns the unique identifier of the panel member.
     *
     * @return the panel member's ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the full name of the panel member.
     *
     * @return the panel member's name
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the full name of the panel member.
     *
     * @param name the name to set; must not be null or blank
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Returns the email address of the panel member.
     *
     * @return the panel member's email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of the panel member.
     *
     * @param email the email to set; must be unique and non-null
     */
    public void setEmail(final String email) {
        this.email = email;
    }

    /**
     * Returns the mobile phone number of the panel member.
     *
     * @return the panel member's mobile number
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * Sets the mobile phone number of the panel member.
     *
     * @param mobile the mobile number to set
     */
    public void setMobile(final String mobile) {
        this.mobile = mobile;
    }

    /**
     * Returns the organization the panel member belongs to.
     *
     * @return the organization name
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * Sets the organization the panel member belongs to.
     *
     * @param organization the organization name to set
     */
    public void setOrganization(final String organization) {
        this.organization = organization;
    }

    /**
     * Returns the job designation or title of the panel member.
     *
     * @return the panel member's designation
     */
    public String getDesignation() {
        return designation;
    }

    /**
     * Sets the job designation or title of the panel member.
     *
     * @param designation the designation to set
     */
    public void setDesignation(final String designation) {
        this.designation = designation;
    }

    /**
     * Returns the hashed password of the panel member.
     *
     * @return the hashed password string
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the password for the panel member.
     *
     * <p>
     * <strong>Note:</strong> Always store a hashed value; never persist a
     * plain-text password.
     * </p>
     *
     * @param password the hashed password to set
     */
    public void setPassword(final String password) {
        this.password = password;
    }

    /**
     * Returns whether the panel member's account is active.
     *
     * @return {@code true} if the account is active; {@code false} otherwise
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the active status of the panel member's account.
     *
     * @param active {@code true} to activate the account; {@code false} to
     *               deactivate it
     */
    public void setActive(final boolean active) {
        this.active = active;
    }

    /**
     * Returns the activation token sent to the panel member's email.
     *
     * @return the activation token, or {@code null} if not yet generated or already
     *         used
     */
    public String getActivationToken() {
        return activationToken;
    }

    /**
     * Sets the activation token for email-based account verification.
     *
     * @param activationToken the token to set
     */
    public void setActivationToken(final String activationToken) {
        this.activationToken = activationToken;
    }

    /**
     * Returns the expiry date and time of the activation token.
     *
     * @return the token expiry timestamp, or {@code null} if not set
     */
    public LocalDateTime getTokenExpiry() {
        return tokenExpiry;
    }

    /**
     * Sets the expiry date and time for the activation token.
     *
     * @param tokenExpiry the expiry timestamp to set
     */
    public void setTokenExpiry(final LocalDateTime tokenExpiry) {
        this.tokenExpiry = tokenExpiry;
    }

    /**
     * Returns the timestamp when this panel member record was created.
     *
     * @return the creation timestamp, or {@code null} if not set
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the timestamp when this panel member record was created.
     *
     * <p>
     * <strong>Note:</strong> This should typically be set once on entity creation,
     * ideally via a {@code @PrePersist} lifecycle hook.
     * </p>
     *
     * @param createdAt the creation timestamp to set
     */
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Returns the timestamp when this panel member record was last updated.
     *
     * @return the last update timestamp, or {@code null} if not set
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the timestamp when this panel member record was last updated.
     *
     * @param updatedAt the update timestamp to set
     */
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
