"""
Question 3:
Write a generator function that yields square numbers up to N.
"""


def generate_square_numbers(limit: int):
    """
    Generate square numbers from 1 to the given limit.

    yield is used because it returns one square at a time without storing all values.
    """

    for number in range(1, limit + 1):
        yield number ** 2


def main() -> None:
    """Print square numbers generated by the generator."""

    for square in generate_square_numbers(5):
        print(square)


if __name__ == "__main__":
    main()
