package com.example.springbootapp.component;

import org.springframework.stereotype.Component;

@Component
public class LongMessageFormatter implements MessageFormatter {

    @Override
    public String getSupportedType() {
        return "LONG";
    }

    @Override
    public String format(String context) {

        String topic = (context != null && !context.isBlank())
                ? context
                : "your request";

        return "================ LONG MESSAGE REPORT ================\n" +
               "Topic        : " + topic + "\n" +
               "Status       : Processed Successfully\n" +
               "Priority     : HIGH\n" +
               "Generated By : MessageFormatter System\n" +
               "------------------------------------------------------\n" +
               "Details      : The system has received your request for '" + topic + "' and\n" +
               "               processed it using LONG format strategy.\n" +
               "               This includes structured output with metadata.\n" +
               "------------------------------------------------------\n" +
               "Result       : Operation completed without errors\n" +
               "======================================================";
    }
}